apiVersion: v1
kind: Service
metadata:
  name: proxy-svc
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
  type: NodePort
